version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: fondo_postgres
    restart: always
    environment:
      POSTGRES_USER: fondo_user
      POSTGRES_PASSWORD: fondo_password
      POSTGRES_DB: fondo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

    